package com.sai.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.sai.bo.StudentBo;
import com.sai.dto.StudentDto;
import com.sai.idGenerator.IdGenerator;
import com.sai.repo.StudentRepository;

@Service
@Transactional
public class StudentServiceImpl implements IStudentService {

	@Autowired
	private StudentRepository repo;

	@Override
	public StudentDto findStudentById(String id) {
		StudentDto dto = new StudentDto();
		Optional<StudentBo> optional = repo.findById(id);
		// findById will search based on the default id generated by mongodb
		BeanUtils.copyProperties(optional.get(), dto);
		return dto;
	}

	@Override
	public StudentDto saveStudent(StudentDto dto) {
		dto.setSid(IdGenerator.generateId());
		StudentBo bo = new StudentBo();
		BeanUtils.copyProperties(dto, bo);
		StudentBo save = repo.save(bo);
		BeanUtils.copyProperties(save, dto);
		return dto;
	}

	@Override
	public List<StudentDto> findAllByNameInAndAgeBetween(String[] names, Integer ageAbove, Integer ageBelow) {
		List<StudentBo> boList = repo.findAllByNameInAndAgeBetween(names, ageAbove, ageBelow);
		List<StudentDto> dtoList = new ArrayList<StudentDto>();
		boList.forEach(bo->{
			StudentDto dto = new StudentDto();
			BeanUtils.copyProperties(bo, dto);
			dtoList.add(dto);
		});
		return dtoList;
	}

	@Override
	public void deleteStudentById(String id) {
		Optional<StudentBo> optional = repo.findById(id);
		if(optional.isPresent()) {
			System.out.println("Document found...");
			repo.deleteById(id);
			System.out.println("Document deleted successfully");
		}
		else
			System.out.println("Document not found");
	}

	


}
