package com.sai;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

import com.sai.dto.StudentDto;
import com.sai.service.IStudentService;
import com.sai.service.StudentServiceImpl;

@SpringBootApplication
public class SpringMongoDbCrudOpsApplication {

	public static void main(String[] args) {
		ApplicationContext context = SpringApplication.run(SpringMongoDbCrudOpsApplication.class, args);
		IStudentService service = context.getBean(StudentServiceImpl.class);
		System.out.println(service.saveStudent(new StudentDto("sai",24,"guntur")));
		System.out.println(service.findStudentById("64c1dede81544054cfa4c991"));//default id generated by mongodb
		System.out.println("========================================");
		service.findAllByNameInAndAgeBetween(new String[] {"sai","hari","vamsi"}, 22, 25).forEach(System.out::println);;
		service.deleteStudentById("64c1dede81544054cfa4c991");
	}

}
